apiVersion: v1
kind: AppConfig
spec:
  server:
    bind:
      host: 0.0.0.0
      port: 8080
    ssl:
      enable: false
      certificate:
      certificateKey:
  db:
    path: ./data/kubepi.db
  session:
    expires: 24
  jwt:
    key: kubepi-secret-key